build:
  tests:
    image: olafurpg/scalafix:0.0.1
    environment:
      - COURSIER_CACHE=.cache/coursier
    commands:
      - ./bin/scalafmt --dir .cache/scalafmt --version 0.4.5 --test
      - sbt -Dsbt.ivy.home=.cache/ivy2 clean test
  publish:
    image: olafurpg/scalafix:0.0.1
    environment:
      - BINTRAY_USERNAME=$$BINTRAY_USERNAME
      - BINTRAY_API_KEY=$$BINTRAY_API_KEY
    commands:
      - ./bin/bintray.sh
    when:
      event: push # merge into master only, not pull requests.
      branch: [master, 4.x]
cache:
  mount:
    - .cache
